// The film of `big-bang` — the editorial layer, and nothing else.
//
// Generated by scripts/film/write-script.mjs (gpt-5.6-terra, which SAW the
// frames). Hand-edit freely: this file is the source of truth from here on and
// is only regenerated when `film.mjs` is run with --rewrite.
//
// PACING IS WORD COUNT. Every shot lasts exactly as long as its line takes to
// say, measured from the real voice alignment — there is deliberately no
// seconds knob. To hold a beat longer, give it more to say. `hold` applies
// only to a shot whose narration is empty.
export default {
  title: "THE LONG NOW",
  endCard: "13.8 BILLION YEARS, IN ONE BREATH.\nKEEP LOOKING UP.",

  score: {
    prompt: "A single evolving documentary score that begins as near-silent cosmic awe, opens into luminous orchestral wonder, becomes earthy and intimate with human history, then resolves in fragile spaciousness.",
    acts: [
    {
      name: "Before Light", fromBeat: 0, toBeat: 10,
      text: "Nearly inaudible low drones, glassy particles, and restrained sub-bass gradually acquire pulse and brightness as the early universe becomes transparent.",
      styles: ["sub-bass drone","granular chimes","distant choir textures","slowly widening stereo field"],
      negativeStyles: ["heroic brass","EDM percussion","comedic sounds","trailer impacts"],
    },
    {
      name: "The Universe Wakes", fromBeat: 11, toBeat: 18,
      text: "Sparse piano harmonics and high strings emerge from darkness, expanding into luminous, weightless orchestral texture for stars, galaxies, and the cosmic web.",
      styles: ["felt piano harmonics","high strings","soft analog shimmer","weightless choir"],
      negativeStyles: ["busy rhythm section","melodramatic climax","harsh synth leads","military drums"],
    },
    {
      name: "A Living World", fromBeat: 19, toBeat: 29,
      text: "Warm, tactile low strings and woodwinds bring the scale down from dust and impact to water, cells, oceans, and the violence of extinction.",
      styles: ["warm cellos","breathy woodwinds","muted hand percussion","subtle organic ambience"],
      negativeStyles: ["cheerful folk music","sci-fi laser effects","constant percussion","sentimental swell"],
    },
    {
      name: "The Recent Flash", fromBeat: 30, toBeat: 38,
      text: "A restrained human pulse grows from firelight and clay into industrial tension, then falls away to a clear, reflective final chord over Earth.",
      styles: ["soft frame drum","intimate piano","muted strings","distant industrial resonance"],
      negativeStyles: ["triumphant anthem","aggressive electronic beat","patriotic march","bombastic finale"],
    },
    ],
  },

  shots: [
  {
    beat: 0,
    narration: "At the edge of our map, this small glow marks a universe younger than the shortest interval physics can describe, where gravity has not yet separated from the other forces.",
    travel: 2.1,
  },
  {
    beat: 1,
    narration: "Then space itself expands faster than light, not through space but as space, stretching a region smaller than a proton to something larger than a grapefruit.",
    travel: 2.4,
  },
  {
    beat: 2,
    narration: "When that surge ends, the bright field is almost perfectly smooth, except for faint density ripples: quantum fluctuations enlarged to cosmic size, every future galaxy sketched in noise.",
    travel: 2.0,
    look: { from: { yaw: -12, pitch: 0 }, to: { yaw: 12, pitch: 0 } },
  },
  {
    beat: 3,
    narration: "As it cools, the Higgs field settles, the electroweak force splits, and massless particles gain mass. The four distinct forces we know are now in place.",
    travel: 1.8,
  },
  {
    beat: 4,
    narration: "Soon the strong force binds freely moving quarks into threes, making the first protons and neutrons as the plasma cools past about two trillion degrees.",
    travel: 1.7,
  },
  {
    beat: 5,
    narration: "But matter survives by the narrowest margin: for every billion antiparticles, about a billion and one particles remain, the rounding error that becomes every star, planet, and you.",
    travel: 1.8,
    look: { from: { yaw: -12, pitch: 0 }, to: { yaw: 12, pitch: 0 } },
  },
  {
    beat: 6,
    narration: "One second in, neutrinos stop interacting and simply leave. They are still travelling through your room now, about 340 in every cubic centimetre, under two degrees above absolute zero.",
    travel: 2.0,
  },
  {
    beat: 7,
    narration: "Between roughly ten seconds and twenty minutes, nuclei fuse into helium, with traces of deuterium and lithium, locking in a recipe of about three-quarters hydrogen and one-quarter helium.",
    travel: 2.2,
  },
  {
    beat: 8,
    narration: "For a few hundred thousand years, all is an opaque, million-degree glare. Free electrons scatter every ray before an image can form, so there is nowhere to see.",
    travel: 2.0,
  },
  {
    beat: 9,
    narration: "After fifty thousand years of radiation smoothing every attempted structure, matter finally outweighs it, and gravity begins deepening the faint ripples left by inflation.",
    travel: 1.8,
  },
  {
    beat: 10,
    narration: "At about 3,000 degrees, electrons join nuclei and the fog clears. Light can travel straight at last, still arriving today as the 2.725-degree cosmic microwave background.",
    travel: 2.1,
  },
  {
    beat: 11,
    narration: '',
    hold: 5,
    travel: 1.5,
    look: { from: { yaw: -10, pitch: 0 }, to: { yaw: 10, pitch: 0 } },
  },
  {
    beat: 12,
    narration: "Out of that hundred-million-year darkness, the first stars ignite in dense knots, enormous and blue. Their short lives scatter the first carbon, oxygen, and iron.",
    travel: 2.3,
    look: { from: { yaw: -12, pitch: 0 }, to: { yaw: 12, pitch: 0 } },
  },
  {
    beat: 13,
    narration: "Those lights gather into the first true galaxies. In 2024, James Webb confirmed JADES-GS-z14-0, shining less than 300 million years after the Big Bang.",
    travel: 2.0,
  },
  {
    beat: 14,
    narration: "Their radiation strips electrons from the hydrogen between galaxies. By about a billion years in, intergalactic space is clear to ultraviolet light, as it remains today.",
    travel: 2.1,
  },
  {
    beat: 15,
    narration: "Star formation reaches its peak, roughly ten times faster than now, while colliding galaxies and feeding black holes blaze at their brightest. From here, the universe slowly quiets.",
    travel: 2.3,
    look: { from: { yaw: -10, pitch: 0 }, to: { yaw: 10, pitch: 0 } },
  },
  {
    beat: 16,
    narration: "Across the largest scales, galaxies gather in sheets and filaments between dense clusters, leaving immense near-empty voids: inflation's tiny ripples grown under gravity for billions of years.",
    travel: 2.2,
    look: { from: { yaw: -5, pitch: 0 }, to: { yaw: 5, pitch: 1 } },
  },
  {
    beat: 17,
    narration: "Then, after eight billion years of slowing expansion, matter thins and dark energy takes over. It makes up about 68% of the universe, and we do not know what it is.",
    travel: 2.0,
  },
  {
    beat: 18,
    narration: "Within one barred spiral, about 100,000 light years across, a few hundred billion stars circle a black hole four million times the mass of the Sun.",
    travel: 2.4,
  },
  {
    beat: 19,
    narration: "Here a cold molecular cloud collapses into the Sun, while the leftover 0.14% becomes a spinning disc of gas and dust: every planet, moon, asteroid, and comet.",
    travel: 2.3,
  },
  {
    beat: 20,
    narration: "In that young system, a Mars-sized body glances off Earth. Debris enters orbit and coalesces within a century or so into the Moon, once far closer than it is now.",
    travel: 2.0,
    sfx: [
      { name: "planetary-impact-rumble", prompt: "Deep distant impact rumble with a short shower of granular debris, cinematic but restrained, no musical tone.", at: 0.55, seconds: 2.8 },
    ],
    look: { from: { yaw: -10, pitch: 0 }, to: { yaw: 10, pitch: 0 } },
  },
  {
    beat: 21,
    narration: "As Earth cools, water can remain liquid. Zircon crystals from Western Australia, 4.4 billion years old, suggest oceans existed within about 150 million years of the planet itself.",
    travel: 2.1,
  },
  {
    beat: 22,
    narration: "Somewhere in these waters, chemistry begins copying itself. Stromatolites around 3.5 billion years old are the oldest widely accepted traces, and every living thing shares an ancestor from around this time.",
    travel: 2.2,
    look: { from: { yaw: -12, pitch: 0 }, to: { yaw: 12, pitch: 0 } },
  },
  {
    beat: 23,
    narration: "Cyanobacteria vent oxygen as waste until the oceans can absorb no more. It floods the atmosphere, poisoning almost everything alive, yet making everything that follows possible.",
    travel: 2.0,
  },
  {
    beat: 24,
    narration: "Then one microbe engulfs another and keeps it. The captive becomes the mitochondrion, giving cells the energy budget for complexity and founding every plant, animal, and fungus.",
    travel: 1.9,
  },
  {
    beat: 25,
    narration: "After three billion years of almost entirely single cells, the Ediacaran seas fill with large soft bodies, fronds and discs and ribbons unlike anything alive today.",
    travel: 2.1,
    look: { from: { yaw: -10, pitch: 0 }, to: { yaw: 10, pitch: 0 } },
  },
  {
    beat: 26,
    narration: "Then, in perhaps twenty million years, almost every major animal body plan alive today appears: eyes, shells, limbs, guts, predators, and the arms race that still runs.",
    travel: 2.0,
  },
  {
    beat: 27,
    narration: "Plants colonise bare rock and, over the next hundred million years, build soils and forests. Arthropods follow, and by 380 million years ago the first vertebrates reach land.",
    travel: 2.2,
  },
  {
    beat: 28,
    narration: "That living world is nearly undone when Siberian eruptions burn coal and release carbon. The oceans acidify and lose oxygen; around 81% of marine species vanish, taking ten million years to recover.",
    travel: 2.1,
  },
  {
    beat: 29,
    narration: "Later, an asteroid strikes the Yucatán Peninsula at around 20 kilometres per second. Fires spread worldwide, dust blocks the sun for years, and the non-avian dinosaurs end.",
    travel: 1.8,
    sfx: [
      { name: "asteroid-impact-blast", prompt: "A distant colossal impact blast, low thunderous boom followed by a brief hiss of falling debris, realistic and not exaggerated.", at: 0.35, seconds: 3.4 },
    ],
  },
  {
    beat: 30,
    narration: "Much later in Africa, our lineage separates from the one leading to chimpanzees. There is no first human, only populations walking upright a little more often over millions of years.",
    travel: 2.3,
    look: { from: { yaw: -4, pitch: 0 }, to: { yaw: 4, pitch: 1 } },
  },
  {
    beat: 31,
    narration: "Homo erectus appears, tall and long-legged, the first hominin to leave Africa. Somewhere across more than a million years, our ancestors learn to control fire.",
    travel: 2.0,
    sfx: [
      { name: "distant-campfire-crackle", prompt: "Very distant small campfire crackle in open night air, faint and dry, with no voices or wildlife.", at: 1.05, seconds: 2.6 },
    ],
  },
  {
    beat: 32,
    narration: "Eventually, Homo sapiens appears. The oldest fossils, from Jebel Irhoud in Morocco, are about 300,000 years old, alongside Neanderthals, Denisovans, and other humans.",
    travel: 2.0,
  },
  {
    beat: 33,
    narration: "A wave of modern humans spreads across Eurasia and reaches Australia by boat. Within forty thousand years, our species occupies every continent except Antarctica, alone among humans.",
    travel: 2.2,
  },
  {
    beat: 34,
    narration: "As the last ice age ends, people in the Fertile Crescent begin planting gathered seeds. Stored food brings surplus, settlements, specialists, property, and hierarchy, with similar changes elsewhere.",
    travel: 2.1,
  },
  {
    beat: 35,
    narration: "With settlements come workshops. The wheel begins flat, spinning clay in Mesopotamia, before someone turns it upright, adds an axle and a box, and makes distance shrink.",
    travel: 2.0,
    look: { from: { yaw: -3, pitch: 0 }, to: { yaw: 3, pitch: 0 } },
  },
  {
    beat: 36,
    narration: "In Uruk, accountants press marks into clay for grain and livestock. Tallies become signs, signs become language, and information outlives the person holding it.",
    travel: 1.8,
    look: { from: { yaw: -4, pitch: 1 }, to: { yaw: 4, pitch: -1 } },
  },
  {
    beat: 37,
    narration: "Much later, Britain burns coal at scale, and human muscle stops setting the limit. Within two centuries, population, energy use, and atmospheric carbon bend sharply upward.",
    travel: 2.1,
    look: { from: { yaw: -4, pitch: 0 }, to: { yaw: 4, pitch: 1 } },
    sfx: [
      { name: "distant-industrial-hum", prompt: "Low distant industrial furnace and city machinery hum beneath a smoky night atmosphere, subdued and realistic.", at: 0.8, seconds: 3.1 },
    ],
  },
  {
    beat: 38,
    narration: "Now, thirteen point eight billion years of physics has arranged a small fraction of matter into something able to ask where it came from. Recorded history is the last one-thousandth of one percent.",
    travel: 2.5,
  },
  ],
};
