// The film of `earth-to-mars` — the editorial layer, and nothing else.
//
// Generated by scripts/film/write-script.mjs (gpt-5.6-sol, which SAW the
// frames). Hand-edit freely: this file is the source of truth from here on and
// is only regenerated when `film.mjs` is run with --rewrite.
//
// PACING IS WORD COUNT. Every shot lasts exactly as long as its line takes to
// say, measured from the real voice alignment — there is deliberately no
// seconds knob. To hold a beat longer, give it more to say. `hold` applies
// only to a shot whose narration is empty.
export default {
  title: "PAD TO MARS",
  endCard: "FOLLOW THE NEXT JOURNEY\nKEEP LOOKING OUTWARD",

  score: {
    prompt: "A restrained orchestral-electronic score rises from grounded launch percussion into a spacious, self-sustaining cruise movement, tightens into abrasive entry rhythm, and resolves in a fragile surface coda.",
    acts: [
    {
      name: "Departure", fromBeat: 0, toBeat: 8,
      text: "Low strings and restrained percussion gather mechanical weight, accelerate through ascent, briefly open in orbit, then surge beneath the injection burn.",
      styles: ["low strings","muted brass","restrained taiko pulses","sub-bass engine texture","gradual orchestral acceleration"],
      negativeStyles: ["triumphal fanfare","heroic military march","busy trailer percussion","bright pop rhythm"],
    },
    {
      name: "Cruise", fromBeat: 9, toBeat: 17,
      text: "A spacious harmonic bed carries long silences, with slow synth movement, isolated piano tones and faint mechanical textures marking the almost motionless crossing.",
      styles: ["sustained analog synths","glass harmonics","isolated felt piano","very slow harmonic rhythm","subtle spacecraft resonance","austere and weightless"],
      negativeStyles: ["melodramatic swells","constant percussion","ambient wash without structure","sentimental piano melody","science-fiction bleeps"],
    },
    {
      name: "Arrival", fromBeat: 18, toBeat: 25,
      text: "Low pulse and metallic rhythm gather as Mars fills the frame, breaking into turbulent noise and compressed percussion through entry before stopping abruptly at touchdown.",
      styles: ["tense low ostinato","bowed metal","granular air textures","compressed percussion","dissonant strings","abrupt dynamic release"],
      negativeStyles: ["action-movie bombast","oversized brass","dance beat","horror stingers","continuous wall of noise"],
    },
    {
      name: "Surface", fromBeat: 26, toBeat: 27,
      text: "The score thins to a few warm, suspended tones, leaving room for the still landscape and the final point of light.",
      styles: ["soft viola harmonics","felt piano overtones","warm analog drone","spare and contemplative"],
      negativeStyles: ["uplifting anthem","sentimental climax","heavy bass","rhythmic percussion","grand resolution"],
    },
    ],
  },

  shots: [
  {
    beat: 0,
    narration: "At dusk, a Mars transfer stack waits beside its tower, taller and heavier than an Apollo stack, with almost all its mass again given to propellant.",
    travel: 1.8,
    look: { from: { yaw: -4, pitch: 0 }, to: { yaw: 4, pitch: 1 } },
  },
  {
    beat: 1,
    narration: "Seven seconds after ignition, light blooms at its base; engines prove themselves under restraint, water protects the trench, and the hold-down arms finally let go.",
    travel: 1.6,
    sfx: [
      { name: "launch-ignition-rumble", prompt: "A massive rocket ignition building through deep ground vibration, turbulent exhaust and deluge water, ending with a heavy clamp release.", at: 0.2, seconds: 7 },
    ],
  },
  {
    beat: 2,
    narration: "The tower falls behind as the stack rolls and tips, trading the straight climb for the sideways speed its orbit actually needs.",
    travel: 1.5,
  },
  {
    beat: 3,
    narration: "By about fourteen kilometres, speed and air make their worst combination; the flame holds steady while the engines ease through the load, then push again.",
    travel: 1.7,
  },
  {
    beat: 4,
    narration: "At two minutes thirty-five seconds, the spent first stage tumbles clear and the second lights above it, turning one bright vehicle into two.",
    travel: 1.5,
    sfx: [
      { name: "stage-separation-thump", prompt: "A pair of forceful mechanical separation thumps followed by the deep vibration of an upper-stage engine lighting, heard through the vehicle structure.", at: 0.6, seconds: 3.5 },
    ],
  },
  {
    beat: 5,
    narration: "Now the horizon is curved and lit beneath a black, star-filled sky: above about a hundred kilometres, there is no meaningful air left to scatter blue.",
    travel: 1.8,
  },
  {
    beat: 6,
    narration: "The flame vanishes in a low parking orbit, and the stage coasts two hundred kilometres above an Earth so large it fills the lower frame.",
    travel: 2.0,
    sfx: [
      { name: "engine-cutoff", prompt: "A sustained rocket vibration cutting off sharply, leaving a few quiet metallic creaks inside the coasting vehicle.", at: 0.4, seconds: 2.5 },
    ],
  },
  {
    beat: 7,
    narration: "One quiet circuit carries it across the terminator, from glare into darkness, where city lights begin to draw the coastlines below.",
    travel: 2.1,
  },
  {
    beat: 8,
    narration: "Then, at one hour thirty-six minutes, the engine relights. A burn lasting minutes fixes four decades of distance and eight and a half months of time.",
    travel: 1.7,
    sfx: [
      { name: "trans-mars-burn", prompt: "A powerful sustained engine burn heard as dense low-frequency vibration transmitted through a spacecraft hull.", at: 0.5, seconds: 6 },
    ],
  },
  {
    beat: 9,
    narration: "Behind the departing craft, Earth is now a receding disc ten thousand kilometres away, with the Moon beside it as a small, separate point.",
    travel: 2.2,
  },
  {
    beat: 10,
    narration: '',
    hold: 7.5,
    travel: 2.4,
    look: { from: { yaw: -5, pitch: 1 }, to: { yaw: 5, pitch: -1 } },
  },
  {
    beat: 11,
    narration: '',
    hold: 6.5,
    travel: 2.3,
    look: { from: { yaw: 0, pitch: 0 }, to: { yaw: 8, pitch: 1 } },
  },
  {
    beat: 12,
    narration: "When the pale ring of Earth's orbit falls behind the ship's wider arc, fifty-seven days have passed. Earth and Sun are points, and the ship will never again be as fast as on departure.",
    travel: 2.2,
    // STATIC on the film gate (motion 0.9 against a 1.2 floor). The scale law
    // holds the subject at a constant apparent size through the cruise and
    // there is nothing else in frame, so the picture is composed correctly and
    // simply does not change. Authored look drift is the documented cure and
    // rule 8 permits it — `look` is a second INPUT axis, authored here rather
    // than dragged, so the frame stays a pure function of (u, look).
    look: { from: { yaw: -9, pitch: 0 }, to: { yaw: 9, pitch: 0 } },
  },
  {
    beat: 13,
    narration: '',
    hold: 7,
    travel: 2.1,
    // The worst place in the film to freeze: seven seconds of deliberate
    // silence on a picture that was not changing (motion 1.2, exactly at the
    // floor). Slower than the spoken shots — 10° across 7 s is ~1.4°/s, under
    // the rate at which a drift stops reading as parallax and starts reading
    // as a camera move.
    look: { from: { yaw: -5, pitch: -1 }, to: { yaw: 5, pitch: 1 } },
    sfx: [
      { name: "solar-array-deploy", prompt: "Quiet electric deployment motors, hinged solar panels unfolding, light structural flex and several crisp locking latches inside an otherwise silent spacecraft.", at: 0.6, seconds: 5 },
    ],
  },
  {
    beat: 14,
    narration: '',
    hold: 6.5,
    travel: 2.2,
    sfx: [
      { name: "course-correction-pulse", prompt: "A short muted correction-thruster pulse transmitted through the spacecraft, with a faint valve click and brief hull vibration.", at: 1.5, seconds: 2.5 },
    ],
  },
  {
    beat: 15,
    narration: "By the time the outer ring crosses the trajectory, two hundred and twenty-five days have gone. The first half took fifty-seven. The transfer slows at the far end, and the bright point at the crossing is rendezvous, not coincidence.",
    travel: 2.3,
  },
  {
    beat: 16,
    narration: "At two hundred and fifty-nine days, one ochre point ahead is brighter than the surrounding stars. Mars is finally present, but not yet a world.",
    travel: 2.1,
    // motion 0.6 — the flattest shot in the film. Mars is a point held at a
    // constant size by the scale law, so nothing in frame moves at all.
    look: { from: { yaw: -7, pitch: 0 }, to: { yaw: 7, pitch: 0 } },
  },
  {
    beat: 17,
    narration: "Then the colour acquires an edge. The target is still only a tiny ochre mark in the black, but at last its shape has become the subject.",
    travel: 1.9,
    // motion 0.7. Drifts the opposite way from the shot before it, so two
    // adjacent near-identical frames also differ in which way the world is
    // sliding — the cut between them stops reading as a jump back.
    look: { from: { yaw: 7, pitch: 0 }, to: { yaw: -7, pitch: 0 } },
  },
  {
    beat: 18,
    narration: "Soon Mars fills a third of the frame: rust-red dust, a bright white polar cap and a hard terminator. The colour across it is iron oxide.",
    travel: 1.7,
  },
  {
    beat: 19,
    narration: "Closer still, the ochre disc swells behind the ship until broad bands of light and shadow, rather than an isolated point, occupy the view.",
    travel: 1.6,
  },
  {
    beat: 20,
    narration: "The cruise hardware peels away as the capsule drops toward rust-coloured ground. At one hundred and twenty-five kilometres, air begins to matter; after two hundred and fifty-nine days, everything left will take under seven minutes.",
    travel: 1.4,
    sfx: [
      { name: "entry-interface-buffet", prompt: "A thin atmospheric hiss rising into irregular hull vibration as a capsule first bites into the Martian atmosphere.", at: 0.8, seconds: 5 },
    ],
  },
  {
    beat: 21,
    narration: "Fifty-five seconds into entry, the orange-white sheath widens around the capsule. An atmosphere about one per cent of Earth's surface pressure is enough at this speed.",
    travel: 1.3,
    sfx: [
      { name: "plasma-sheath-roar", prompt: "An intense filtered rush of plasma and turbulent air with stressed heat-shield vibration, powerful but not explosive.", at: 0.4, seconds: 5.5 },
    ],
  },
  {
    beat: 22,
    narration: "Four minutes in, a single canopy snaps open above the falling capsule, but the thin air leaves powered descent with real work still to do.",
    travel: 1.3,
    sfx: [
      { name: "parachute-deploy", prompt: "A sharp deployment mortar pop followed by a violent fabric snap, lines pulling taut and canopy cloth straining in thin air.", at: 0.5, seconds: 4 },
    ],
  },
  {
    beat: 23,
    narration: "One minute later, the heat shield falls away, exposing the lander's underside and legs. With no more atmosphere to lean on, the descent must be flown, not fallen.",
    travel: 1.3,
    sfx: [
      { name: "heat-shield-separation", prompt: "Explosive separation bolts cracking, followed by a hollow metallic shell release and brief structural rattle.", at: 0.5, seconds: 3 },
    ],
  },
  {
    beat: 24,
    narration: "At five minutes thirty, the retro engines light beneath the exposed lander, replacing the parachute with a narrow exhaust plume as the rust-coloured ground expands below.",
    travel: 1.2,
    sfx: [
      { name: "retro-engine-ignition", prompt: "Compact descent rockets igniting with a hard mechanical bark, settling into a focused low rumble with faint dust impact below.", at: 0.4, seconds: 5 },
    ],
  },
  {
    beat: 25,
    narration: "At six minutes forty seconds, the engines cut and the dust begins to fall. Four legs stand on rust-coloured ground, at the point chosen when the hold-down arms released.",
    travel: 1.4,
    sfx: [
      { name: "touchdown-contact", prompt: "Descent engines cutting abruptly, four subdued footpad impacts on compact soil, then a short patter of settling dust and complete stillness.", at: 0.7, seconds: 4 },
    ],
  },
  {
    beat: 26,
    narration: "An hour later, the first view is almost plain: a rust-coloured horizon and scattered basalt rocks, extraordinary only because this is Mars.",
    travel: 2.2,
    look: { from: { yaw: -5, pitch: 0 }, to: { yaw: 5, pitch: -2 } },
  },
  {
    beat: 27,
    narration: "By dusk, eleven hours after landing, one low point of light remains near where the Sun set. Earth has become Mars's evening star.",
    travel: 2.5,
    look: { from: { yaw: 4, pitch: 0 }, to: { yaw: -4, pitch: 1 } },
  },
  ],
};
