// Assemble a posting kit for a rendered explainer — one file with everything
// needed to actually publish, so nothing is written by hand at posting time.
//
//   node scripts/make-postkit.mjs <explainer-id>
//
// Reads: src/explainers/<id>/meta.js, src/explainers/<id>/video.js (its
// optional `platforms` block), and whatever is already rendered under
// renders/<id>/. Writes renders/<id>/POST.md.
//
// The copy itself is authored in video.js during the scripting stage, while the
// script's context is hot — this script only collects it. Anything missing
// comes out as an explicit TODO rather than being silently dropped, so a
// half-filled kit is visible instead of looking complete.
//
//   // src/explainers/<id>/video.js
//   platforms: {
//     youtube: { title: '…', description: '…', tags: ['…'] },
//     shorts:  { title: '…', hashtags: ['#…'] },
//   }
import { existsSync, statSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { pathToFileURL } from 'node:url';

const id = process.argv.slice(2).find((a) => !a.startsWith('--'));
if (!id) {
  console.error('usage: node scripts/make-postkit.mjs <explainer-id>');
  process.exit(1);
}
const outRoot = resolve('renders', id);
if (!existsSync(outRoot)) {
  console.error(`nothing rendered yet: ${outRoot} does not exist — run export-video.mjs first`);
  process.exit(1);
}

const load = async (p) => (existsSync(p) ? (await import(pathToFileURL(p))).default : null);
const meta = await load(resolve(`src/explainers/${id}/meta.js`));
const editorial = await load(resolve(`src/explainers/${id}/video.js`));
const platforms = editorial?.platforms ?? {};

const TODO = (what) => `**TODO** — ${what} (author it in \`src/explainers/${id}/video.js\` → \`platforms\`)`;
const mb = (p) => `${(statSync(p).size / 1048576).toFixed(1)} MB`;

// duration comes from the rendered timeline rather than ffprobe (ffmpeg-static
// ships ffmpeg only, and the timeline is authoritative for what was rendered)
const duration = (format) => {
  const p = join(outRoot, `${format}-timeline.json`);
  if (!existsSync(p)) return null;
  const t = JSON.parse(readFileSync(p, 'utf8'));
  return t.length ? Number(t[t.length - 1].end).toFixed(1) : null;
};

const fileRows = [];
for (const format of ['short', 'long']) {
  const d = duration(format);
  for (const kind of ['final', 'captioned', 'master']) {
    const p = join(outRoot, `${format}-${kind}.mp4`);
    if (existsSync(p)) {
      fileRows.push(`| \`${format}-${kind}.mp4\` | ${format === 'short' ? '9:16' : '16:9'} | ${d ? `${d}s` : '—'} | ${mb(p)} |`);
    }
  }
}

const thumbsDir = join(outRoot, 'thumbs');
const thumbs = existsSync(thumbsDir)
  ? readdirSync(thumbsDir).filter((f) => /\.(jpg|png)$/i.test(f))
  : [];

const yt = platforms.youtube ?? {};
const sh = platforms.shorts ?? {};

const md = `# Posting kit — ${meta?.title ?? id}

Generated by \`scripts/make-postkit.mjs\`. Copy is authored in
\`src/explainers/${id}/video.js\`; regenerate after changing it.

## Files

| File | Ratio | Duration | Size |
| --- | --- | --- | --- |
${fileRows.length ? fileRows.join('\n') : '| _nothing rendered_ | — | — | — |'}

- \`*-final.mp4\` — captioned + narrated. **This is what you post.**
- \`*-captioned.mp4\` — silent with captions, for posting over trending audio.
- \`*-master.mp4\` — clean silent master, reusable for re-cuts.

## Thumbnails (long-form)

${thumbs.length ? thumbs.map((f) => `- \`thumbs/${f}\``).join('\n') : `_none — run_ \`node scripts/make-thumbnails.mjs ${id}\``}

Clean plates: add the headline text on top before uploading.

## YouTube (long-form, 16:9)

**Title**
${yt.title ? `\n> ${yt.title}\n` : `\n${TODO('YouTube title')}\n`}
**Description**
${yt.description ? `\n\`\`\`\n${yt.description}\n\`\`\`\n` : `\n${TODO('YouTube description')}\n`}
**Tags**
${yt.tags?.length ? `\n${yt.tags.join(', ')}\n` : `\n${TODO('YouTube tags')}\n`}

## Shorts / Reels / TikTok (9:16)

**Title / caption**
${sh.title ? `\n> ${sh.title}\n` : `\n${TODO('short-form title')}\n`}
**Hashtags**
${sh.hashtags?.length ? `\n${sh.hashtags.join(' ')}\n` : `\n${TODO('short-form hashtags')}\n`}

## Source

- Explainer: \`src/explainers/${id}/\`
- Summary: ${meta?.summary ?? '_none_'}
`;

const outPath = join(outRoot, 'POST.md');
writeFileSync(outPath, md);
const todos = (md.match(/\*\*TODO\*\*/g) ?? []).length;
console.log(`postkit: ${outPath}${todos ? ` — ${todos} TODO(s) still unauthored` : ''}`);
