// The film of `voyager` — the editorial layer, and nothing else.
//
// Generated by scripts/film/write-script.mjs (gpt-5.6-terra, which SAW the
// frames). Hand-edit freely: this file is the source of truth from here on and
// is only regenerated when `film.mjs` is run with --rewrite.
//
// PACING IS WORD COUNT. Every shot lasts exactly as long as its line takes to
// say, measured from the real voice alignment — there is deliberately no
// seconds knob. To hold a beat longer, give it more to say. `hold` applies
// only to a shot whose narration is empty.
export default {
  title: "BEYOND THE SUN",
  endCard: "VOYAGER CONTINUES\nFOLLOW THE JOURNEY",

  score: {
    prompt: "A restrained, spacious electronic-orchestral score moves from curious propulsion to luminous planetary wonder, then thins into solitary, weightless ambience.",
    acts: [
    {
      name: "Departure", fromBeat: 0, toBeat: 3,
      text: "Quiet pulse, low synth warmth, and sparse piano establish a deliberate departure into open space.",
      styles: ["restrained analog synth pulse","soft felt piano","subtle orbital percussion","expansive ambient pads"],
      negativeStyles: ["trailer braams","marching snare","upbeat corporate music","bombastic fanfare"],
    },
    {
      name: "Giant Worlds", fromBeat: 4, toBeat: 8,
      text: "The music broadens with warm strings and glassy electronic detail, carrying discovery without becoming triumphant.",
      styles: ["warm sustained strings","celestial bell tones","slow modular synth arpeggios","low orchestral swell"],
      negativeStyles: ["heroic brass fanfare","action percussion","comedic wonder","aggressive EDM"],
    },
    {
      name: "Outer Passage", fromBeat: 9, toBeat: 16,
      text: "A colder, slower palette accompanies Saturn through Triton, with delicate high textures over a deep, patient drone.",
      styles: ["icy granular synths","distant choir pad","minimal piano harmonics","slow bass drone"],
      negativeStyles: ["sentimental pop ballad","heavy drums","horror stingers","retro arcade music"],
    },
    {
      name: "Interstellar", fromBeat: 17, toBeat: 21,
      text: "Instrumentation steadily falls away into near-silence, leaving a fragile harmonic glow around the final star field.",
      styles: ["near-silent ambient drone","sparse glass harmonics","soft radio-like texture","fading piano resonance"],
      negativeStyles: ["big finale","victory anthem","loud percussion","abrupt ending"],
    },
    ],
  },

  shots: [
  {
    beat: 0,
    narration: "In the late 1970s, a configuration that appears roughly every 176 years set Jupiter, Saturn, Uranus and Neptune in line, allowing two Voyager probes to borrow each planet's gravity toward the next.",
    travel: 2.5,
  },
  {
    beat: 1,
    narration: "First, at fourteen thousand kilometres up, the spent stages fall away and Voyager unfolds, its magnetometer extending thirteen metres clear; Voyager 2 took the slower route first, and Voyager 1 overtook it two weeks later.",
    travel: 2.1,
    sfx: [
      { name: "boom-deployment", prompt: "Brief mechanical release clacks and unfolding metal latches from a spacecraft, dry and delicate, with no rocket roar.", at: 0.5, seconds: 1.3 },
    ],
  },
  {
    beat: 2,
    narration: "Past Mars' orbital distance, instruments power up for a year and a half of nearly featureless coasting toward Jupiter.",
    travel: 1.8,
    look: { from: { yaw: -5, pitch: 0 }, to: { yaw: 5, pitch: 2 } },
  },
  {
    beat: 3,
    narration: "Even the asteroid belt offers more emptiness than danger: all its rock totals less than the Moon's mass, spread wide enough for Voyager to cross without a realistic chance of hitting anything.",
    travel: 2.2,
  },
  {
    beat: 4,
    narration: "Then Jupiter, once a point, slowly widens into these bands over months, its more than three hundred Earth masses becoming the dominant force on the path.",
    travel: 2.4,
  },
  {
    beat: 5,
    narration: "Across those bands, a storm wider than Earth has raged in the southern hemisphere for at least as long as telescopes have watched, turning above a world with no solid ground.",
    travel: 1.7,
  },
  {
    beat: 6,
    narration: "Nearby, Jupiter's tides squeeze Io until it becomes the solar system's most volcanically active body, with plumes hundreds of kilometres high erupting in real time, a discovery nobody predicted.",
    travel: 1.9,
    sfx: [
      { name: "io-volcanic-plume", prompt: "A brief, distant volcanic gas burst with a soft granular eruption texture, restrained and not cinematic.", at: 1.1, seconds: 1.5 },
    ],
  },
  {
    beat: 7,
    narration: "Europa offers a quieter surprise: long straight fractures score an icy surface with almost no impact craters, evidence it is young and resurfaced from below, perhaps above an ocean.",
    travel: 2.0,
  },
  {
    beat: 8,
    narration: "The tour now pays off. Without firing an engine, Voyager steals a sliver of Jupiter's orbital momentum, bends away toward Saturn, and gains several kilometres a second, while Jupiter loses too little momentum ever to measure.",
    travel: 2.6,
  },
  {
    beat: 9,
    narration: "It coasts for another two years, now faster than on the outbound leg, as the Sun shrinks beyond the size it held at Earth.",
    travel: 1.8,
    look: { from: { yaw: -5, pitch: 0 }, to: { yaw: 5, pitch: 1 } },
  },
  {
    beat: 10,
    narration: "Ahead, Saturn's rings almost vanish edge-on: just seventy metres thick but hundreds of thousands of kilometres wide, their plane can disappear from sight.",
    travel: 2.3,
    // STATIC at mot 0.3 in the dry run with no drift authored. Edge-on rings
    // hold a constant apparent size under the scale law and there is nothing
    // else in frame. The pitch term is the useful half: it opens and closes the
    // ring plane, which is the subject. 16 deg of yaw over ~12s is 1.33 deg/s.
    look: { from: { yaw: -8, pitch: 2 }, to: { yaw: 8, pitch: -2 } },
  },
  {
    beat: 11,
    // The film's one wordless shot, moved here by hand. It was on the Pale Blue
    // Dot, where silence left the most famous moment in the story unnamed over
    // a frame indistinguishable from the one before it. This is the strongest
    // picture in the film (occ 0.87, con 0.29, mot 18.4), it sits at the
    // midpoint just after the densest passage, and the previous line has
    // already said what the rings are — so it genuinely carries alone.
    //
    // It is also load-bearing for the GATE: the duck is measured as the score's
    // level inside speech windows versus between them, and a film with no
    // wordless shot has no windows between them. Every shot then abuts the
    // next, the only gap is the 1.2 s lead-in, and the check reads a working
    // duck as -46.5 dB. Silence somewhere is what makes the duck measurable.
    narration: '',
    hold: 4.5,
    travel: 2.0,
  },
  {
    beat: 12,
    narration: "Inside that glitter, Titan keeps its ground hidden beneath an orange nitrogen atmosphere thicker than Earth's, opaque enough that Voyager's cameras could not see through it to any surface at all.",
    travel: 1.8,
  },
  {
    beat: 13,
    narration: "That close pass sends Voyager 1 north, out of the planets' plane, to study Titan up close, trading away further planetary encounters; Voyager 2 takes another line, preserving its way to Uranus and Neptune.",
    travel: 2.5,
    look: { from: { yaw: -6, pitch: 0 }, to: { yaw: 6, pitch: 2 } },
  },
  {
    beat: 14,
    narration: "On that path, Uranus rolls around the Sun, its axis tilted almost ninety degrees from every other planet's, a nearly featureless pale cyan world where methane absorbs sunlight's red end.",
    travel: 2.2,
  },
  {
    beat: 15,
    narration: "Farther still, Neptune is deepest blue and the windiest place yet found in the solar system, where supersonic winds over two thousand kilometres an hour are driven by internal heat.",
    travel: 2.1,
  },
  {
    beat: 16,
    narration: "Its largest moon, Triton, orbits backwards, evidence it was captured, while geysers rise kilometres from a thin nitrogen atmosphere above the coldest surface Voyager visited.",
    travel: 1.9,
    sfx: [
      { name: "triton-nitrogen-geyser", prompt: "A short, delicate pressurized gas jet with faint icy grain texture, distant and subdued.", at: 0.8, seconds: 1.4 },
    ],
    // STATIC at mot 0.5 measured on the real render, the film's only flagged
    // shot. Triton holds a constant apparent size under the scale law and the
    // escort adds no parallax at this range, so nothing in frame changes for
    // the whole line. 18 deg of yaw over the shot's 14.6 s is 1.23 deg/s, under
    // the 1.5 that starts reading as a camera move. The previous film needed
    // the same correction on the same beat.
    look: { from: { yaw: -9, pitch: 1 }, to: { yaw: 9, pitch: -1 } },
  },
  {
    beat: 17,
    narration: "At Pluto's average distance, the route still does not turn toward Pluto: Voyager 2 had already committed to Triton. Beyond, the Kuiper belt is a far larger belt of icy debris, with Pluto its largest known member.",
    travel: 2.4,
  },
  {
    beat: 18,
    // The director made this wordless. Hand-edited back to a spoken line: the
    // frame is a glare-scattered field almost indistinguishable from the Kuiper
    // shot before it, so silence here reads as a stall on a repeated picture,
    // and it leaves the film's second-most affecting moment unnamed. The line
    // is written to the GLARE, which is what the frame actually shows — the
    // dot itself is under a pixel and is not visible, and the copy says so.
    narration: "On 14 February 1990, at Carl Sagan's request, Voyager 1 turned its camera back through scattered sunlight like this and photographed Earth: a single point, less than a tenth of a pixel wide. Everyone who has ever lived, lived on it.",
    travel: 2.0,
  },
  {
    beat: 19,
    narration: "In August 2012, Voyager 1 crossed the heliopause, where plasma density jumped roughly forty-fold in days. At this boundary of the Sun's influence, particles from the Sun give way to particles from elsewhere in the galaxy; eight years earlier, the solar wind slowed below sound some thirty AU further in.",
    travel: 2.7,
  },
  {
    beat: 20,
    // The emotional close, and deliberately the longest line in the film.
    // Pacing is word count, so length here IS screen time on the record. Every
    // fact is in beat 20's own copy; "these marks" points at the etched
    // diagrams actually visible on the record's face in this frame.
    narration: "Bolted to each spacecraft is a gold-plated copper record. On it are sounds and images of Earth and greetings in fifty-five languages, and with it a stylus, and these marks: the instructions for playing it. Nobody knows whether anything will ever find it. It was aimed anyway, at whoever might, long after everyone who built it is gone.",
    travel: 2.2,
    look: { from: { yaw: -5, pitch: 0 }, to: { yaw: 5, pitch: 1 } },
  },
  {
    beat: 21,
    narration: "At Proxima Centauri, the nearest star to the Sun, 4.0134 light-years away, Voyager 1 would need roughly seventy-four thousand years at about seventeen kilometres a second, and it is not headed there. The Sun is just another point of light among the others.",
    travel: 2.8,
    look: { from: { yaw: -8, pitch: 0 }, to: { yaw: 8, pitch: 2 } },
  },
  ],
};
